name: Delete Kubernetes Components
description: Run kubectl and helm inspection commands in a namespace

inputs:
  namespace:
    description: Kubernetes namespace to recreate
    required: true

runs:
  using: composite
  steps:
    - name: Recreate Kubernetes Components
      shell: bash
      run: |
        kubectl delete ingress --all -n adapt-authoring
        kubectl apply -f ./docker/components/adapt-ingress.yaml -n adapt-authoring

 



