apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pull in all Kompose-generated manifests

resources:
  - ../kompose/app-deployment.yaml
  - ../kompose/app-service.yaml
  - ../kompose/mongo-deployment.yaml
  - ../kompose/migration-deployment.yaml
  - ../kompose/db-persistentvolumeclaim.yaml
  - ../kompose/storage-persistentvolumeclaim.yaml

