# syntax=docker/dockerfile:1.7

FROM cgr.dev/ssc-spc.gc.ca/mongodb:latest-dev

WORKDIR /migration

# Copy files first
COPY new-migrations/dump ./dump
COPY new-migrations/data ./data
COPY new-migrations/framework ./framework
COPY docker/migration/migrate.sh ./migrate.sh

# Fix permissions + make script executable
USER root
RUN chmod +x ./migrate.sh \
    && chown -R mongodb:mongodb /migration

# Drop privileges
USER mongodb

# Run migration
CMD ["./migrate.sh"]