# syntax=docker/dockerfile:1.7

FROM cgr.dev/ssc-spc.gc.ca/mongodb:latest-dev

WORKDIR /migration

# Copy files first
COPY new-migrations/dump ./dump
COPY new-migrations/data ./data
COPY new-migrations/framework ./framework
COPY docker/migration/migrate.sh ./migrate.sh

# Fix permissions + make script executable
USER root
RUN apk add bash \
    && chmod +x ./migrate.sh \
    && mkdir -p /app/storage /app/data /app/temp \
    && chown -R 65532:65532 /migration /app

# Drop privileges using numeric UID
USER 65532

# Run migration
CMD ["/bin/bash", "./migrate.sh"]