apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          volumeMounts:
            - name: temp
              mountPath: /app/temp
      volumes:
        - name: temp
          persistentVolumeClaim:
            claimName: temp
