apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - mongo-service.yaml
  - migration-job.yaml
  - app-rbac.yaml

patches:
  - path: mongo-init.yaml
    target:
      kind: Deployment
      name: mongo

  - path: app-init.yaml
    target:
      kind: Deployment
      name: app

  - path: app-wait-for-migration.yaml
    target:
      kind: Deployment
      name: app

  - path: migration-delete.yaml
    target:
      kind: Deployment
      name: migration
  
  - path: app-remove-command.yaml
    target:
      kind: Deployment
      name: app
 
  - path: app-fix-workdir.yaml
    target:
      kind: Deployment
      name: app

  - path: app-image-pull.yaml
    target:
      kind: Deployment
      name: app


labels:
  - includeSelectors: true
    pairs:
      environment: dev
