apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - mongo-service.yaml


patches:
  - path: mongo-init.yaml
    target:
      kind: Deployment
      name: mongo
  - path: migration-init.yaml
    target:
      kind: Deployment
      name: migration
  - path: app-init.yaml
    target:
      kind: Deployment
      name: app



labels:
  - includeSelectors: true
    pairs:
      environment: dev
