# kustomize:patch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  template:
    spec:
      initContainers:
        - name: init-mongo-data
          # Switched from Docker Hub busybox to Chainguard FIPS-validated busybox
          image: cgr.dev/ssc-spc.gc.ca/busybox-fips:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /data/db && \
              chown -R 65532:65532 /data/db
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
            - mountPath: /data/db
              name: db

      containers:
        - name: mongo
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"