apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp
  namespace: adapt-authoring
  labels:
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi