name: Check Kubernetes Components and Import Secrets

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

env:
  NAMESPACE: adapt-authoring

jobs:
  CheckK8Components:
    runs-on: arc-runners-dshp-dev

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Azure + AKS Login     
      - name: Azure + AKS Login
        uses: ./.github/actions/actions          

      # Step 3: Check Kubernetes Components
      - name: Check Kubernetes Components
        uses: ./.github/actions/check-components
        with:
          namespace: ${{ env.NAMESPACE }}

