name: Check Kubernetes Components 

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

env:
  NAMESPACE: adapt-authoring
  roleId: ${{ secrets.APPROLE_ROLE_ID }}
  secretId: ${{ secrets.APPROLE_SECRET_ID }}


jobs:
  CheckK8Components:
    runs-on: arc-runners-dshp-dev

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Azure + AKS Login     
      - name: Azure + AKS Login
        uses: ./.github/actions/actions
        with:
          roleId: ${{ env.roleId}}
          secretId: ${{ env.secretId }}
      
      - name: Get Vault Secrets
        uses: hashicorp/vault-action@v3.4.0
        id: secrets
        with:
          url: https://vault.dev-dp.admin.dts-stn.com
          method: kubernetes
          role: adapt-authoring
          secrets: |
            adapt-authoring/data/AZURE K8S_CLUSTER_NAME | K8S_CLUSTER_NAME ;
            secrets-github-k8s-auth-test/data/helloworld test | TEST_secret

          

      # Step 3: Check Kubernetes Components
      - name: Check Kubernetes Components
        uses: ./.github/actions/check-components
        with:
          namespace: ${{ env.NAMESPACE }}

