name: Check Kubernetes Components 

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

env:
  NAMESPACE: adapt-authoring
  roleId: ${{ secrets.APPROLE_ROLE_ID }}
  secretId: ${{ secrets.APPROLE_SECRET_ID }}


jobs:
  CheckK8Components:
    runs-on: arc-runners-dshp-dev

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Azure + AKS Login     
      - name: Azure + AKS Login
        uses: ./.github/actions/actions
        with:
          roleId: ${{ env.roleId}}
          secretId: ${{ env.secretId }}
      
      # Create Pull Secret
      - name: Log in to Chainguard Registry
        run: |
          docker login cgr.dev \
            --username ${{ secrets.CGR_USERNAME }} \
            --password ${{ secrets.CGR_PASSWORD }}

      # Chainguard login
      - name: Create Kubernetes image pull secret
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=cgr.dev \
            --docker-username=${{ secrets.CGR_USERNAME }} \
            --docker-password=${{ secrets.CGR_PASSWORD }} \
            -n ${{ env.NAMESPACE }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # Step 3: Check Kubernetes Components
      - name: Check Kubernetes Components
        uses: ./.github/actions/check-components
        with:
          namespace: ${{ env.NAMESPACE }}

