name: Recreate Kubernetes Components 

on:
  workflow_dispatch: # Allows manual triggering


env:
  NAMESPACE: adapt-authoring
  roleId: ${{ secrets.APPROLE_ROLE_ID }}
  secretId: ${{ secrets.APPROLE_SECRET_ID }}


jobs:
  RecreateK8Components:
    runs-on: arc-runners-dshp-dev

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Azure + AKS Login     
      - name: Azure + AKS Login
        uses: ./.github/actions/actions
        with:
          roleId: ${{ env.roleId}}
          secretId: ${{ env.secretId }}

      # Step 3: Delete Kubernetes Components
      - name: Delete Kubernetes Components
        uses: ./.github/actions/recreate-components
        with:
          namespace: ${{ env.NAMESPACE }}

      # Step 4: Check Kubernetes Components
      - name: Check Kubernetes Components
        uses: ./.github/actions/check-components
        with:
          namespace: ${{ env.NAMESPACE }}