name: SonarQube  Scan 

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

env:
  NAMESPACE: adapt-authoring
  roleId: ${{ secrets.APPROLE_ROLE_ID }}
  secretId: ${{ secrets.APPROLE_SECRET_ID }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


jobs:
  build:
    name: Build and analyze
    runs-on: arc-runners-dshp-dev
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'  # Adjust to your project's Java version
          distribution: 'temurin'
      
      - name: Build project
        run: mvn clean compile  # Use ./gradlew build if using Gradle
      
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}

